# this is config for staging

config: staging
upload:
  url: toppi-backend.bimasaktisanjaya.net
  port: 443
  protocol: https
help_upload:
  url: https://toppi-backend.bimasaktisanjaya.net/upload
test_ocr:
  # url: https://toppi-backend.bimasaktisanjaya.net/upload?test=1
  # url: https://toppi-entrypoint-compat-v3.bimasaktisanjaya.net/upload?test=1
  url: https://toppi-entrypoint-v3.bimasaktisanjaya.net/test
