name: Flutter Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Clean Flutter project
        run: flutter clean

      # - name: Configure Git for Private Packages
      #   run: |
      #     git config --global url."https://${{ secrets.PACKAGE_TOKEN }}@github.com/".insteadOf "https://github.com/"
      #     git config --global --get-regexp url

      - name: Install dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: build/app/outputs/flutter-apk/*.apk
    